export const ADD_ = 'ADD';
export const REMOVE = 'REMOVE';
export const SETENTRIES = 'SETENTRIES';

export const SETENTRYSAVED = 'SETENTRYSAVED';

export const SETLOADING = 'SETLOADING';

export const SETLISTID = 'SETLISTID';




//Category

export const SETCATEGORIES = 'SETCATEGORIES';
export const CHANGEINPUTVALUE = 'CHANGEINPUTVALUE';
export const SETPARENTID = 'SETPARENTID';
export const ADDTOCATEGORIES = 'ADDTOCATEGORIES';
export const CHANGEISLOADING = 'CHANGEISLOADING';
export const CREATELIST = 'CREATELIST';
